use yew::prelude::*;

#[function_component(App)]
fn app() -> Html {
    html! {
        <body>
            <h1>{ "This page is generated by rust" }</h1>
            <div>
                <p>{ "I think it's nice " }</p>
            </div>
        </body>
    }
}

fn main() {
    yew::start_app::<App>();
}
